version: '3.8'
name: pokemon-api

services:
  mongodb:
    image: mongo:latest
    container_name: pokemon-api-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: pokemon-api-app
    depends_on:
      - mongodb
    environment:
      MONGODB_URI: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017/pokemon_api
      PORT: 8080
    env_file:
      - .env.template
    ports:
      - '8080:8080'

volumes:
  mongodb_data:
