name: pokemon-api

services:
  mongodb:
    image: mongo:latest
    container_name: pokemon-api-dev-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data_dev:/data/db
volumes:
  mongodb_data_dev:
