name: Pokemon API

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-test:
    name: api
    runs-on: ubuntu-20.04

    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017

    env:
      NODE_ENV: ci
      MONGODB_URI: mongodb://localhost:27017

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - run: make install
      - run: make lint-check
      - run: cp .env.template .env
      - run: make test
